---
title: __DATASCI 350 - Data Science Computing__
semester: "Fall 2026"
lang: en-GB
author: 
  - Danilo Freire
fontfamily: libertine
monofont: inconsolata
monofontoptions: scaled=.95
fontsize: 12pt
spacing: double
geometry: 
  - top=2cm
  - bottom=2cm
  - left=2cm
  - right=2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
highlight-style: arrow
pdf-engine: pdflatex
format: 
    pdf:
      template: syllabus-template.latex
      toc: true
      toc-depth: 1
      number-sections: false
editor: 
  render-on-save: true
---

# Course Description

Welcome to [DATASCI 350](https://github.com/danilofreire/datasci350)! This course introduces key tools in modern data science, focusing on three essential aspects: reliability, reproducibility, and robustness. We will cover the [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface), version control with [Git](https://git-scm.com/) and [GitHub](https://github.com/), and reproducible reports using [Quarto](https://quarto.org/) and [Jupyter Notebooks](https://jupyter.org/). You will then work with language models, first running one on your own laptop with [Ollama](https://ollama.com/), then calling hosted models from Python, and finally building a small retrieval system over your own documents. We will rent machines in the cloud with [Amazon Web Services](https://aws.amazon.com/), collect data from web APIs with [requests](https://requests.readthedocs.io/), and process it at scale with [Polars](https://pola.rs/), [DuckDB](https://duckdb.org/), and [Dask](https://www.dask.org/). We finish with [Docker](https://www.docker.com/) and containerisation. 

By working with real-world datasets and problems, students will gain hands-on experience using these tools and methods to extract insights from data. This course will develop technical skills and critical thinking needed to solve complex data challenges. Upon completion, students will be prepared to apply these tools to their own research and professional work.

# Learning Objectives

By the end of this course, students will be able to:

- Use the command line interface to manage files and directories.
- Work with version control systems to track changes in code and collaborate with others.
- Create reproducible reports and presentations.
- Use language models and coding agents responsibly to assist with programming tasks.
- Collect data from web APIs and web pages, and process it at scale.
- Understand the basics of containerisation and parallel computing.
 
# Course Requirements

Some knowledge of programming is recommended, and familiarity with basic data manipulation and visualisation techniques is helpful. However, no prior experience with the tools covered in the course is required.

In terms of software, you will need to install the following tools: [Anaconda distribution of Python 3.x](https://www.anaconda.com/), [VS Code](https://code.visualstudio.com/), [Git](https://git-scm.com/), [GitHub Desktop](https://github.com/apps/desktop), [Quarto](https://quarto.org/), [Ollama](https://ollama.com/), and [Docker](https://www.docker.com/). Several lectures also need Python packages that Anaconda does not ship. Install them with `pip install ollama openai python-dotenv requests pyarrow polars duckdb dask joblib`. You will open two free accounts during the course, one on [OpenRouter](https://openrouter.ai/) for Lecture 14 and one on [Amazon Web Services](https://aws.amazon.com/) for Lectures 16 and 17. Neither costs anything if you follow the steps in the lecture READMEs.

Please feel free to reach out if you have any questions about the course content or your readiness to take the class.

# Materials

This course is designed to be self-contained, providing all the necessary resources and materials to succeed in mastering the core concepts. However, students are encouraged to explore the following suggested books, online courses, and documentation to deepen their understanding of the topics covered in the course. Everything listed here is free to read.

## Suggested Books

- [Data Science on the Command Line](https://www.datascienceatthecommandline.com/) by Jeroen Janssens
- [Pro Git](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub
- [The Turing Way](https://book.the-turing-way.org/) by The Turing Way Community
- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/README.html) by Allen Downey
- [Speech and Language Processing](https://web.stanford.edu/~jurafsky/slp3/) by Dan Jurafsky and James H. Martin. Note: the chapters on embeddings and transformers explain what Lectures 12 and 15 use.
- [DuckDB in Action](https://motherduck.com/duckdb-book/) by Mark Needham, Michael Hunger, and Michael Simons
- [Free programming books](https://github.com/EbookFoundation/free-programming-books)

### Online Courses

- [MIT: The Missing Semester of Your CS Education](https://missing.csail.mit.edu/)
- [Coursera: Python for Everybody Specialisation](https://www.coursera.org/specializations/python)
- [Class Central: Introduction to Git and GitHub](https://www.classcentral.com/course/introduction-git-github-18060)
- [Hugging Face: LLM Course](https://huggingface.co/learn/llm-course)
- [AWS Skill Builder: Cloud Practitioner Essentials](https://skillbuilder.aws/)
- [Kaggle: Learn](https://www.kaggle.com/learn)

### Documentation

- [Official Python Documentation](https://docs.python.org/3/)
- [NumPy Documentation](https://numpy.org/doc/)
- [Pandas Documentation](https://pandas.pydata.org/docs/)
- [Matplotlib Documentation](https://matplotlib.org/stable/index.html)
- [Quarto Documentation](https://quarto.org/docs/guide/)
- [Git Documentation](https://git-scm.com/doc)
- [GitHub Documentation](https://docs.github.com/en)
- [Ollama Documentation](https://docs.ollama.com/)
- [OpenRouter Documentation](https://openrouter.ai/docs)
- [Requests Documentation](https://requests.readthedocs.io/)
- [Polars Documentation](https://docs.pola.rs/)
- [DuckDB Documentation](https://duckdb.org/docs/)
- [Dask Documentation](https://docs.dask.org/en/latest/)
- [AWS Documentation](https://docs.aws.amazon.com/)
- [Docker Documentation](https://docs.docker.com/)

# Course Information

We will meet every Tuesday and Thursday from 5:30pm to 6:45pm in [Math & Science Center, Room W301](https://maps.app.goo.gl/JAnhzo63ZcT4GgE87). It is important that you read the materials before class. All information about the course is available on the course's GitHub repository at <https://github.com/danilofreire/datasci350>. While I will try to adhere to the course schedule as much as possible, I also want to adapt to your learning pace and style. The syllabus and course plan may change in the semester. Again, please check [the course repository](https://github.com/danilofreire/datasci350) regularly to check for updates. I will also announce any changes in class and via email.

# Software

We will mainly use [Python](https://www.python.org) in this course. Python is a free and powerful programming language that is widely used in data science, machine learning, and scientific computing. I recommend using the [Anaconda distribution](https://www.anaconda.com/products/individual) as it comes with many necessary Python libraries for data analysis, such as [Pandas](https://pandas.pydata.org/), [NumPy](https://numpy.org/), and [Jupyter](https://jupyter.org/). 

You can write your Python code in any text editor, but I recommend [VS Code](https://code.visualstudio.com/) with the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python). [Pycharm](https://www.jetbrains.com/pycharm/) is also well-regarded by developers. If you are feeling adventurous, you can also use [Neovim](https://neovim.io/) with the [coc-pyright](https://github.com/fannheyward/coc-pyright) plugin. That is, if [you can exit the editor](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/). :)

We will collect our own data rather than query a database. Lectures 18 and 19 use [requests](https://requests.readthedocs.io/) to pull data from web APIs, and we save the results as CSV and parquet files. If you want to learn SQL, work through the self-study [DuckDB tutorial](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html) in the course repository. DATASCI 151 also covers SQL basics in more depth than we could here.

We will also use [Jupyter Notebooks](https://jupyter.org/) and [Quarto](https://quarto.org) in class. Jupyter itself comes pre-installed with Anaconda, but please install the [Jupyter extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false) as well. To install Quarto, please follow the instructions on the [official website](https://quarto.org). We will have a hands-on session to learn how to use both of them (but I assume you are already familiar with Jupyter).

Please also install [Docker](https://www.docker.com/) to work with containers. Docker is a platform for developing, shipping, and running applications in containers. Containers allow you to package your application and its dependencies together into a single unit. This makes it easy to ensure that your application will run on any other machine, regardless of any custom settings that machine might have that could differ from the machine that was used for writing and testing the code.

Finally, we will use [GitHub](https://github.com) for version control. Please create a free account on GitHub and install [GitHub Desktop](https://desktop.github.com/) to manage your repositories. We will also use [Git](https://git-scm.com/) in the course. Git is a distributed version control system that allows you to track changes in your codebase and collaborate with others. You can install Git from the [official website](https://git-scm.com/).

To help you get started, I have prepared [six tutorials](https://danilofreire.github.io/datasci350/tutorials.html) for the course:

- [Installing VS Code and connecting it with Anaconda](https://danilofreire.github.io/datasci350/01-vscode-anaconda-tutorial.html)
- [Jupyter Notebook and Markdown](https://danilofreire.github.io/datasci350/02-jupyter-markdown-tutorial.html)
- [Opening a free educational account on GitHub](https://danilofreire.github.io/datasci350/03-github-tutorial.html)
- [SQL essentials with DuckDB](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html)
- [Web scraping with Python](https://danilofreire.github.io/datasci350/05-web-scraping-tutorial.html)
- [Setting up WSL on Windows](https://danilofreire.github.io/datasci350/06-wsl-tutorial.html)

Read tutorials 01 to 03 in order at the start of the semester. Windows users should also read tutorial 06 before Lecture 03. Tutorials 04 and 05 cover material we do not teach in class, and you can read them whenever you need them.

# Office Hours

I am very flexible with office hours, and we can schedule an online meeting at any time that works for you. Feel free to send me a message at [danilo.freire@emory.edu](mailto:danilo.freire@emory.edu), and I will likely reply within a few hours. If you prefer, you can meet me in the afternoon at my office. My office address is in the [Psychology and Interdisciplinary Sciences Building, 36 Eagle Row, room 480](https://maps.app.goo.gl/bGHKwasQyp5MnQND6). If possible, please email me before coming to ensure that no two students book the same time slot.

# Academic Integrity

Upon every individual who is a part of Emory University falls the responsibility for maintaining in the life of Emory a standard of unimpeachable honour in all academic work. The [Honor Code of Emory College](https://catalog.college.emory.edu/academic/policies-regulations/honor-code.html) is based on the fundamental assumption that every loyal person of the University not only will conduct his or her own life according to the dictates of the highest honor, but will also refuse to tolerate in others action which would sully the good name of the institution. Academic misconduct is an offense generally defined as any action or inaction which is offensive to the integrity and honesty of the members of the academic community. Any suspected case of academic misconduct will be referred to the Emory Honor Council.

# Artificial Intelligence

Students have to submit ten problem sets and complete five in-class quizzes. You are allowed to use AI to assist with your assignments, and you may also use AI tools during quizzes. However, any errors or omissions resulting from the use of AI tools are your responsibility, and you must always double-check your work. Remember to cite all sources used in your problem sets and projects, including AI tools. Please include a note at the end of any document indicating that AI was used in its development. Quizzes carry an explanation requirement, which is described in the grading policy below. Using AI tools in a manner prohibited in this course syllabus constitutes cheating under the Emory Honor Code and is thus a form of academic misconduct.

# Special Needs and Accessibility Services

I am committed to providing necessary accommodations to ensure all students have an equal opportunity to succeed in this course. Students with medical or health conditions that may impact their academic performance should visit the [Department of Accessibility Services (DAS)](http://accessibility.emory.edu/) to determine eligibility for appropriate accommodations. Those who receive accommodations should provide me with an Accommodation Letter from DAS at the beginning of the semester or as soon as the accommodation is granted. Please note that DAS accommodations, such as extra time or quiet spaces, will apply only to quizzes, not assignments. This is because assignments are released in advance, allowing students to work at their own pace. Athletes and students with other commitments should also inform me of any scheduling conflicts at the beginning of the semester. I will do my best to accommodate these students, but I cannot guarantee that all requests will be granted. If you have any questions or concerns, please contact me.

# English Language Learners

Emory University welcomes students from around the country and the world, and the unique perspectives international and multilingual students bring enrich the campus community. To empower multilingual learners, an array of support is available including language and culture workshops and individual appointments. For more information about English Language Learning support at Emory, please contact the ELLP Specialists at <https://writingcenter.emory.edu>. No student will be penalised for their command of the English language.

# Assignments and Grading Policy

**Problem Sets (50%).** There will be ten problem sets throughout the course. These assignments are designed to reinforce concepts covered in lectures and readings, and to provide hands-on practice with statistical programming. Problem sets will include a mix of theoretical questions and practical applications. They will be assigned regularly and must be completed individually. All ten problem sets are in the course repository from the first day of class, so you can start any of them whenever you like. The dates in the schedule are the rhythm I mark to, not the moment the work appears. Please acknowledge any sources you used in your work, including textbooks, articles, and AI resources. *Any assignment submitted after the due date/time will be penalised by 10% per day*. Please submit your assignments as Jupyter Notebooks (`.ipynb`) or `.pdf` files via Canvas or email until midnight on the due date.

**Class Quizzes (30%).** Students will also take five in-class quizzes throughout the semester. These quizzes will be based on the lectures from the previous weeks. They will be designed to test your understanding of the material and your ability to apply the concepts to new problems. Quizzes will be open-book and open-notes, and students have the entire class period to complete them. They are individual assessments, and students are not allowed to discuss the questions with their classmates in class. You may use AI tools during a quiz, on the same terms as any other resource. *You must be able to explain every command and answer you submit.* After each quiz I select about five students at random and ask them to walk me through part of their work. Students who cannot explain what they submitted will lose marks at my discretion, up to and including a zero for the quiz, depending on how much of the work they can account for.

**Final Project (20%)**: For the final project, you will work in groups of three to four to create a short report. This report will require you to apply the tools and methods we have covered in class to a real-world dataset. You should host your report in a GitHub repository, use Quarto for the document, and collect the data through the World Bank API or another public API you clear with me. Make sure to include visualisations and statistical analyses as well. Your repository must also include a Dockerfile, because the report has to render inside a container on my machine. The project is due on the last day of class. You can read the full [project instructions](https://github.com/danilofreire/datasci350/blob/main/project/project-instructions.pdf) and clone the [starter repository](https://github.com/danilofreire/datasci350-project-starter), which comes with a working Dockerfile and a data pull script.

# Grading Scale

Each student's final grade will be based on the following:

\small

| Grade | A       | A-      | B+      | B       | B-      | C+      | C       | C-      | D+      | D       | F    |
|-------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|------|
| Range | 93\% and above | 90-92.9\%| 87-89.9\%| 83-86.9\%| 80-82.9\%| 77-79.9\%| 73-76.9\%| 70-72.9\%| 67-69.9\%| 60-66.9\%| <60\% |

\normalsize

# Course Outline and Suggested Readings

The lecture notes cover all the necessary material for the course, and the weekly suggested readings are recommended for those who want to deepen their understanding of the course topics. As mentioned above, the course outline is subject to change, and I will update the syllabus if needed. Please remember to check the course [GitHub repository](https://github.com/danilofreire/datasci350) regularly. Lecture notes, assignments, and other materials will be posted there as the course progresses.

## Module 01: Introduction

### August 27, 2026:

- Syllabus and course repository: <https://github.com/danilofreire/datasci350>.
- Lecture 01: [Welcome to DATASCI 350 - Introduction](https://danilofreire.github.io/datasci350/lectures/lecture-01/01-introduction.html).
- [Course tutorials: installing Anaconda and VS Code, Jupyter and Markdown, and opening a free educational account on GitHub](https://github.com/danilofreire/datasci350/tree/main/tutorials).

Suggested references:

- Cleveland, W. S. (2001). [Data science: An action plan for expanding the technical areas of the field of statistics](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1751-5823.2001.tb00477.x). International Statistical Review, 69(1), 21-26.
- Donoho, D. (2017). [50 Years of Data Science](https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1384734). Journal of Computational and Graphical Statistics, 26(4), 745-766.
- Breiman, L. (2001). [Statistical Modeling: The Two Cultures (with Comments and a Rejoinder by the Author)](https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures-with-comments-and-a/10.1214/ss/1009213726.full). Statistical Science, 16(3), 199-231.
- Brady, H. E. (2019). [The Challenge of Big Data and Data Science](https://www.annualreviews.org/content/journals/10.1146/annurev-polisci-090216-023229). Annual Review of Political Science, 22(1), 297-323.

### September 1, 2026:

- Lecture 02: [Computational Literacy](https://danilofreire.github.io/datasci350/lectures/lecture-02/02-computational-literacy.html).

Suggested references:

- Campbell-Kelly, M., Aspray, W. F., Yost, J. R., Tinn, H., & Díaz, G. C. (2023). [Computer: A History of the Information Machine](https://doi.org/10.4324/9781003263272). Routledge.
- Shalf, J. (2020). [The Future of Computing beyond Moore's Law](https://royalsocietypublishing.org/doi/full/10.1098/rsta.2019.0061). Philosophical Transactions of the Royal Society A, 378(2166), 20190061.
- Wing, J. M. (2006). [Computational Thinking](https://www.cs.cmu.edu/~15110-s13/Wing06-ct.pdf). Communications of the ACM, 49(3), 33-35.
- Videos: [David J. Malan - Abstraction](https://www.youtube.com/watch?v=6V1sr0XV_Ng), [Khan Academy - Hexadecimal Number System](https://www.youtube.com/watch?v=4EJay-6Bioo), [Matthias Wandel - Marble Adding Machine](https://youtu.be/GcDshWmhF4A), [Crash Course - Early Computing](https://www.youtube.com/watch?v=O5nskjZ_GoI) and [Electronic Computing](https://www.youtube.com/watch?v=LN0ucKNX0hc) (the last two are quite entertaining!).

## Module 02: Introduction to the Command-Line Interface and Version Control

### September 3, 2026:

- Lecture 03: [The Command-Line Interface (CLI), Shell Basics, and File Management](https://danilofreire.github.io/datasci350/lectures/lecture-03/03-command-line.html).
- [**Assignment 01**](https://github.com/danilofreire/datasci350/blob/main/assignments/01-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=9a77f4a0-f1ea-498a-b85f-1a8993922f82&hostId=05eb977d-4f8a-440e-9e45-95212b29d103)

Suggested references:

- Janssens, J. (2021). [Data Science at the Command Line: Obtain, Scrub, Explore, and Model Data with Unix Power Tools (2nd ed.)](https://jeroenjanssens.com/dsatcl/). O'Reilly Media.
- Levy, J. (2024). [The Art of Command Line](https://github.com/jlevy/the-art-of-command-line). GitHub.
- Shotts, W. (2019). [The Linux Command Line: A Complete Introduction](https://linuxcommand.org/tlcl.php). No Starch Press.
- Healy, K. (2019). [The Plain Person's Guide to Plain Text Social Science](https://plain-text.co/). Chapters 1-5.

### September 8, 2026:

- Lecture 04: [More Command Line Tools, Text Files and Scripting](https://danilofreire.github.io/datasci350/lectures/lecture-04/04-more-command-line.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=9a77f4a0-f1ea-498a-b85f-1a8993922f82&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- Kerr, D. (2024). [Effective Shell](https://effective-shell.com/).
- Irianto, I. (2021). [Learn Vim (the Smart Way)](https://github.com/iggredible/Learn-Vim).
- Dennis, J. [Your problem with Vim is that you don't grok vi.](https://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118) (Stack Overflow).
- Videos: [freeCodeCamp - Command line crash course](https://www.youtube.com/watch?v=yz7nYlnXLfE&pp=ygUXaG93IHRvIHVzZSBjb21tYW5kIGxpbmU%3D), [Percy Grunwald - Absolute beginner guide to the macOS terminal](https://www.youtube.com/watch?v=aKRYQsKR46I&pp=ygUcdGVybWluYWwgZm9yIGJlZ2lubmVycyBtYWNvcw%3D%3D), [NetworkChuck - 50 macOS tips and tricks using terminal](https://www.youtube.com/watch?v=qOrlYzqXPa8&pp=ygUcdGVybWluYWwgZm9yIGJlZ2lubmVycyBtYWNvcw%3D%3D)

### September 10, 2026:

- Lecture 05: [Version control with Git and GitHub](https://danilofreire.github.io/datasci350/lectures/lecture-05/05-git-github.html).
- **Assignment 01 due (5%).**
- [**Assignment 02**](https://github.com/danilofreire/datasci350/blob/main/assignments/02-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=f3930dce-298d-4610-a365-406fa3088a87&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- Chacon, S. and Straub, B. (2014). [Pro Git](https://git-scm.com/book/en/v2). Apress. (Instructor's note: this is _the book_ on Git).
- GitHub tutorials: [GitHub skills](https://skills.github.com/) (recommended), [Git guides](https://github.com/git-guides), [Best practices for repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/best-practices-for-repositories).
- [Dangit, Git!?!](https://dangitgit.com/). Note: the fix for the commit you did not mean to make, in plain language.

### September 15, 2026:

- Lecture 06: [More Git and GitHub: pull requests, issues, pages, and collaboration features](https://danilofreire.github.io/datasci350/lectures/lecture-06/06-more-git-github.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=eec92538-78d8-4974-ba7b-8f83b5f3b215&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- Perez-Riverol, Y., Gatto, L., Wang, R., Sachsenberg, T., Uszkoreit, J., Leprevost, F. da V., Fufezan, C., Ternent, T., Eglen, S. J., Katz, D. S., Pollard, T. J., Konovalov, A., Flight, R. M., Blin, K., & Vizcaíno, J. A. (2016). [Ten Simple Rules for Taking Advantage of Git and GitHub](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004947). PLOS Computational Biology, 12(7), e1004947.
- Beckman, M. D., Çetinkaya-Rundel, M., Horton, N. J., Rundel, C. W., Sullivan, A. J., & Tackett, M. (2021). [Implementing version control with git and GitHub as a learning objective in statistics and data science courses](https://www.tandfonline.com/doi/pdf/10.1080/10691898.2020.1848485). Journal of Statistics and Data Science Education, 29(sup1), S132-S144.
- Escamilla, E., Klein, M., Cooper, T., Rampin, V., Weigle, M. C., & Nelson, M. L. (2022). [The Rise of GitHub in Scholarly Publications](https://arxiv.org/abs/2208.04895). arXiv preprint arXiv:2208.04895.

### September 17, 2026:

- Lecture 07: [More Git Commands, CLI and Git Practice](https://danilofreire.github.io/datasci350/lectures/lecture-07/07-practice.html).
- **Assignment 02 due (5%).**
- [**Assignment 03**](https://github.com/danilofreire/datasci350/blob/main/assignments/03-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=0c41d485-25b6-44a6-a825-70854f1953cb&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

### September 22, 2026:

- Lecture 08: [Review session for Quiz 01](https://danilofreire.github.io/datasci350/lectures/lecture-08/08-review.html). This session revises everything covered so far and prepares students for Quiz 01 on September 24, which is examinable on Lectures 02-07.

## Module 03: Reproducible Research with Quarto

### September 24, 2026:

- Lecture 09: [Quiz 01: The Command Line, Git and GitHub (6%)](https://github.com/danilofreire/datasci350-quiz01/). Covers Lectures 02-07.
- **Assignment 03 due (5%).**
- [**Assignment 04**](https://github.com/danilofreire/datasci350/blob/main/assignments/04-assignment.ipynb).

Suggested references:

- [Markdown Guide](https://www.markdownguide.org/basic-syntax/).
- [Jupyter Notebooks Documentation](https://jupyter.org/).
- [Course tutorial: Jupyter and Markdown](https://danilofreire.github.io/datasci350/02-jupyter-markdown-tutorial.html)

### September 29, 2026:

- Lecture 10: [Reproducible Research and Literate Programming](https://danilofreire.github.io/datasci350/lectures/lecture-10/10-quarto.html).

Suggested references:

- Sandve, G. K., Nekrutenko, A., Taylor, J., & Hovig, E. (2013). [Ten Simple Rules for Reproducible Computational Research](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285). PLOS Computational Biology, 9(10), e1003285.
- [The Turing Way: Guide for Reproducible Research](https://book.the-turing-way.org/reproducible-research/overview).
- [Quarto: Get Started](https://quarto.org/docs/get-started/).
- Çetinkaya-Rundel, M. & Lowndes, J. S. (2022) [Keynote talk: Hello Quarto: Share • Collaborate • Teach • Reimagine](https://www.youtube.com/watch?v=p7Hxu4coDl8). [Slides](https://mine.quarto.pub/hello-quarto/#/hello-quarto-title) and [source code](https://github.com/mine-cetinkaya-rundel/hello-quarto). This is one of the nicest Quarto presentations I have seen.

### October 1, 2026:

- Lecture 11: [Quarto in Practice](https://danilofreire.github.io/datasci350/lectures/lecture-11/11-more-quarto.html).
- **Assignment 04 due (5%).**
- [**Assignment 05**](https://github.com/danilofreire/datasci350/blob/main/assignments/05-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=b3cb9962-bfcd-4b44-a3f4-4357b1442eda&hostId=05eb977d-4f8a-440e-9e45-95212b29d103)

Suggested references:

- [Quarto Documentation - Presentations](https://quarto.org/docs/presentations/) and [Websites](https://quarto.org/docs/websites/).
- [Quarto Documentation - Code Execution and Freeze](https://quarto.org/docs/projects/code-execution.html).
- [GitHub Pages Documentation](https://docs.github.com/en/pages).
- French, J. (2023). [Creating Websites with Quarto and GitHub Pages (YouTube Playlist)](https://www.youtube.com/playlist?list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo).

## Module 04: AI-Assisted Programming

### October 6, 2026:

- Lecture 12: [Local Language Models](https://danilofreire.github.io/datasci350/lectures/lecture-12/12-local-models.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=ecf9f3d1-7d0d-4ca1-a3a5-a26c5e72427b&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Ollama Documentation](https://docs.ollama.com/) and the [Modelfile Reference](https://docs.ollama.com/modelfile).
- [Ollama Model Library](https://ollama.com/library). Note: browse this before class and pick a model your laptop can hold.
- Wolfram, S. (2023). [What Is ChatGPT Doing, and Why Does It Work?](https://writings.stephenwolfram.com/2023/02/what-is-chatgpt-doing-and-why-does-it-work/).
- Google (2025). [Gemini Prompting Guide](https://services.google.com/fh/files/misc/gemini-for-google-workspace-prompting-guide-101.pdf). Note: the source of the PTCF framework we use to write system prompts.

### October 8, 2026:

- Lecture 13: [Quiz 02: Reproducible Research and Quarto (6%)](https://github.com/danilofreire/datasci350-quiz02/). Covers Lectures 10 and 11.
- **Assignment 05 due (5%).**
- [**Assignment 06**](https://github.com/danilofreire/datasci350/blob/main/assignments/06-assignment.ipynb).

### October 13, 2026: Fall Break (No Classes)


### October 15, 2026:

- Lecture 14: [Calling Models from Your Own Code](https://danilofreire.github.io/datasci350/lectures/lecture-14/14-ai.html).

Note: create a free [OpenRouter](https://openrouter.ai/) account and API key before this class, and set the key's spending limit to $0.00. The steps are in the lecture README.

Suggested references:

- [Ollama API Documentation](https://docs.ollama.com/api) and its [OpenAI compatibility](https://docs.ollama.com/api/openai-compatibility) page. Note: lecture 12 runs Ollama from the terminal, and this lecture calls the same server from Python.
- [OpenRouter Quickstart](https://openrouter.ai/docs/quickstart) and the [model catalogue](https://openrouter.ai/models). Note: filter the catalogue by Prompt pricing "Free" to find a model that costs nothing today.
- [OpenAI Python library](https://github.com/openai/openai-python). Note: despite the name, it is a client for a protocol that Ollama and OpenRouter both speak.
- Willison, S. (2025). [The lethal trifecta for AI agents](https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/).

### October 20, 2026:

- Lecture 15: [Retrieval-Augmented Generation and Fine-Tuning](https://danilofreire.github.io/datasci350/lectures/lecture-15/15-rag-finetuning.html).

Note: install or update Ollama before this class, then run `pip install ollama numpy`. The steps are in the lecture README.
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=8691380c-2ccb-49fa-aab1-471754aeb24c&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Ollama Documentation: Embedding models](https://docs.ollama.com/capabilities/embeddings).
- [EmbeddingGemma on the Ollama model library](https://ollama.com/library/embeddinggemma). Note: this is the model we run in class.
- [Sentence Transformers Documentation](https://sbert.net/). Note: the clearest explanation of what a sentence embedding is and how similarity search uses it.
- [Unsloth Documentation](https://docs.unsloth.ai/). Note: the tool behind the fine-tuning demonstration; you are not expected to run it yourself.

## Module 05: Cloud Computing

### October 22, 2026:

- Lecture 16: [Introduction to Cloud Computing](https://danilofreire.github.io/datasci350/lectures/lecture-16/16-cloud.html).
- **Assignment 06 due (5%).**
- [**Assignment 07**](https://github.com/danilofreire/datasci350/blob/main/assignments/07-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=9a098f1f-ebd6-40cd-aa4e-b8f096683a37&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Amazon Web Services (AWS) Documentation](https://docs.aws.amazon.com/).
- [AWS Free Tier](https://aws.amazon.com/free/). Note: read this before opening an account, and set a zero-spend budget.
- [AWS Cloud Practitioner Tutorial](https://www.w3schools.com/aws/).

### October 27, 2026:

- Lecture 17: [Cloud Computing II: Running Your Own Server on AWS](https://danilofreire.github.io/datasci350/lectures/lecture-17/17-cloud2.html).
- No new assignment this week. Start reading the final project instructions.
- [Instructions for the Final Project](https://github.com/danilofreire/datasci350/tree/main/project).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=1ee46eb8-e667-4132-9895-4dd72ef3c561&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Amazon EC2 Documentation](https://docs.aws.amazon.com/ec2/).
- [AWS CloudShell Documentation](https://docs.aws.amazon.com/cloudshell/). Note: the way out when a key file's permissions will not work on Windows.
- [Ubuntu Server Documentation](https://documentation.ubuntu.com/server/). Note: the instance we launch runs Ubuntu, and `apt` is how you install anything on it.

## Module 06: Getting Data from the Web

### October 29, 2026:

- Lecture 18: [Web APIs and JSON](https://danilofreire.github.io/datasci350/lectures/lecture-18/18-web-apis.html).
- **Assignment 07 due (5%).**
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=ebd517ed-7bf1-447c-8e30-9c5abb75ef16&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Requests: Quickstart](https://requests.readthedocs.io/en/latest/user/quickstart/).
- MDN. [An overview of HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview).
- [World Bank API Documentation](https://datahelpdesk.worldbank.org/knowledgebase/topics/125589). Note: the API behind the final project.
- [Working with JSON](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/JSON).

### November 3, 2026:

- Lecture 19: [Working with APIs in Practice](https://danilofreire.github.io/datasci350/lectures/lecture-19/19-apis-in-practice.html).
- Optional: [Web scraping tutorial](https://danilofreire.github.io/datasci350/05-web-scraping-tutorial.html). Self-study, not examinable.
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=0d1466b5-ef43-4ab3-90aa-c46ae0554f19&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [pandas: json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html). Note: how nested JSON becomes a flat table.
- [python-dotenv Documentation](https://saurabh-kumar.com/python-dotenv/). Note: how an API key stays out of your repository.
- [Apache Parquet Documentation](https://parquet.apache.org/docs/). Note: the format we save results in, and the one Lectures 21 and 22 read back.
- [wbgapi](https://github.com/tgherzog/wbgapi). Note: a Python client for the World Bank API, useful for the final project.

### November 5, 2026:

- Lecture 20: [Quiz 03: AI-Assisted Programming and Cloud Computing (6%)](https://github.com/danilofreire/datasci350-quiz03/). Covers Lectures 12, 14, 15, 16, and 17.
- [**Assignment 08**](https://github.com/danilofreire/datasci350/blob/main/assignments/08-assignment.ipynb).

## Module 07: Scaling and Performance

### November 10, 2026:

- Lecture 21: [Parallel Computing Fundamentals](https://danilofreire.github.io/datasci350/lectures/lecture-21/21-parallel-computing.html).

Suggested references:

- [Python Documentation: concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html).
- [Python Glossary: global interpreter lock](https://docs.python.org/3/glossary.html#term-global-interpreter-lock).
- [joblib Documentation](https://joblib.readthedocs.io/en/stable/).
- [Dask Documentation](https://docs.dask.org/en/latest/).

### November 12, 2026:

- Lecture 22: [Scaling Data Analysis in Practice](https://danilofreire.github.io/datasci350/lectures/lecture-22/22-parallel-automl.html).
- **Assignment 08 due (5%).**
- [**Assignment 09**](https://github.com/danilofreire/datasci350/blob/main/assignments/09-assignment.ipynb).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=a2403e39-2c84-473b-8e78-ea0889581b0c&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Polars User Guide](https://docs.pola.rs/).
- [DuckDB Documentation](https://duckdb.org/docs/).
- [Dask: Best Practices](https://docs.dask.org/en/stable/best-practices.html).

## Module 08: Containers and Reproducibility

### November 17, 2026:

- Lecture 23: [Dependency Management, Virtual Environments, and Containers](https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=8273ae04-10b2-4eee-9b8a-77f97ef43550&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Python Documentation: venv](https://docs.python.org/3/library/venv.html).
- [uv Documentation](https://docs.astral.sh/uv/). Note: the tool we use in class to create environments and lock dependencies.
- [Docker: Get Started](https://docs.docker.com/get-started/).

### November 19, 2026:

- Lecture 24: [Quiz 04: Web APIs and JSON (6%)](https://github.com/danilofreire/datasci350-quiz04/). Covers Lectures 18 and 19.
- **Assignment 09 due (5%).**
- [**Assignment 10**](https://github.com/danilofreire/datasci350/blob/main/assignments/10-assignment.ipynb).

### November 24, 2026:

- Lecture 25: [Docker for Data Science](https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=f2e51b56-a8f6-4178-8656-fec9d42679b1&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

Suggested references:

- [Dockerfile Reference](https://docs.docker.com/reference/dockerfile/).
- [Docker Compose Documentation](https://docs.docker.com/compose/).
- [Jupyter Docker Stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/). Note: ready-made images for data science work.

### November 26, 2026: Thanksgiving Recess (No Classes)


### December 1, 2026:

- Lecture 26: [Course Revision](https://danilofreire.github.io/datasci350/lectures/lecture-26/26-revision.html).
- [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=d19e2d39-f38c-4a1e-9d5d-c3113bd3ad36&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

### December 3, 2026:

- Lecture 27: [Quiz 05: Scaling, Docker and Containers (6%)](https://github.com/danilofreire/datasci350-quiz05/). Covers Lectures 21, 22, 23, and 25.
- **Assignment 10 due (5%).**

### December 8, 2026:

- No lectures.
- Q&A session and final project work time.
- [Final Project due (20%).](https://github.com/danilofreire/datasci350/tree/main/project)

